name: CI
on:
  push:
  release:
    types:
      - created
#  pull_request:
#    types: [opened, synchronize, reopened]

# checkout, install make and try to build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [motortest, motortest_peter, feedcode-front, feedcode-back, greyhash, pcbv2_front, pcbv2_back, pcbv2_test, commander_v2_front, commander_v2_back]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install make
        run: |
          sudo apt update -y
          sudo apt install -y binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi cmake make
          
      - name: Build
        id: build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .
          make -j$(nproc) ${{ matrix.config }}
